# Change this for your own environment. See:
# http://wiki.rubyonrails.org/rails/pages/database.yml
 
development:
  adapter: mysql
  encoding: utf8
  database: usage_record_development
  username: root
  password: 
  socket: /tmp/mysql.sock
 
test:
  adapter: mysql
  encoding: utf8
  database: usage_record_test
  username: root
  password: 
  socket: /tmp/mysql.sock
  
production:
  adapter: mysql
  encoding: utf8
  database: usage_record_production
  username: root
  password: 
  socket: /tmp/mysql.sock